### ISSUE TITLE
ODRefreshControl under NavigationBar

### ISSUE THREAD

**Issue by matrad** [Sephiroth87/ODRefreshControl#77]
Hello,

I recently upgraded to the newest version of ODRefreshControl. With the Upgrade the ODRefreshControl appears under the UINavigationBar.

I checked the Code, and found the part which was removed, this is causing the error.

WHY this part was removed?

![bildschirmfoto 2015-07-21 um 17 24 04](https://cloud.githubusercontent.com/assets/660903/8804713/c5f2f676-2fcd-11e5-8e15-81264c3aaf2a.png)

**Comment by Sephiroth87** [comment]
That part was not in my repo, you were probably using someone else's fork.
You can either try the 2.0 beta version which should handle the same problem, or use/make a fork with that fix
